### ISSUE TITLE
Wheel Theft

### ISSUE THREAD

**Issue by morrisons90** [GerhartPapaGee/Overthrow-Martial-Law#2]
Steeling wheels should be illegal to stop easy stealing of NATO vehicles. EDIT : Change from trying to make it illegal to not allowing the player to ACE interact with Nato (blufor) occupied vehicles.

**Comment by morrisons90** [comment]
![image](https://user-images.githubusercontent.com/10031775/87544730-de9a2d80-c69e-11ea-9eec-c88e4f5d1b88.png)

See to be having issues with the wanted loop

**Comment by deadorbit** [comment]
I see a few dead bodies around the truck, was it working then stopped or what?

**Comment by GerhartPapaGee** [comment]
" I'm considering just disabling any interaction with a vehicle while it belongs to NATO, what do you think?"  This sounds perfect to be honest.  1. the vehicle is only considered Nato "blufor" when occupied by Nato "blufor, at least if I'm understanding what I seen before in the scripting commands.  2.  IRL people, at least people with brains, wouldn't just walk up and start messing with anything on a military vehicle. MaxP did help me fix an exploit that if you parked beside an occupied military vehicle you could just do the "transfer from" and grab all the gear inside it.  Can't remember if you become wanted or what since I only tested it awhile back.

**Comment by GerhartPapaGee** [comment]
I reopened this as I believe that Deadorbits solution is a much better way of dealing with it
